WORLD_NUM = -100

HIT_ZONE = {
        0: "HEAD",
        1: "HEAD", 
        2: "HELMET", 
        3: "TORSO", 
        4: "VEST", 
        5: "LEFT_ARM", 
        6: "RIGHT_ARM",
        7: "GROIN",
        8: "BUTT",
        9: "LEFT_UPPER_LEG",
        10: "RIGHT_UPPER_LEG",
        11: "LEFT_LOWER_LEG",
        12: "RIGHT_LOWER_LEG",
        13: "LEFT_FOOT",
        14: "RIGHT_FOOT"}

HIT_ITEM = {
        1: "UT_MOD_KNIFE",
        2: "UT_MOD_BERETTA",
        3: "UT_MOD_DEAGLE",
        4: "UT_MOD_SPAS",
        5: "UT_MOD_MP5K",
        6: "UT_MOD_UMP45",
        8: "UT_MOD_LR300",
        9: "UT_MOD_G36",
        10: "UT_MOD_PSG1",
        14: "UT_MOD_SR8",
        15: "UT_MOD_AK103",
        17: "UT_MOD_NEGEV",
        19: "UT_MOD_M4",
        20: "UT_MOD_GLOCK",
        21: "UT_MOD_COLT1911",
        22: "UT_MOD_MAC11",
        23: "UT_MOD_BLED",
        24: "UT_MOD_KICKED",
        25: "UT_MOD_KNIFE_THROWN"}

DEATH_CAUSE = {
        1: "MOD_WATER",
        3: "MOD_LAVA",
        5: "UT_MOD_TELEFRAG",
        6: "MOD_FALLING",
        7: "UT_MOD_SUICIDE",
        9: "MOD_TRIGGER_HURT",
        10: "MOD_CHANGE_TEAM",
        12: "UT_MOD_KNIFE",
        13: "UT_MOD_KNIFE_THROWN",
        14: "UT_MOD_BERETTA",
        15: "UT_MOD_DEAGLE",
        16: "UT_MOD_SPAS",
        17: "UT_MOD_UMP45",
        18: "UT_MOD_MP5K",
        19: "UT_MOD_LR300",
        20: "UT_MOD_G36",
        21: "UT_MOD_PSG1",
        22: "UT_MOD_HK69",
        23: "UT_MOD_BLED",
        24: "UT_MOD_KICKED",
        25: "UT_MOD_HEGRENADE",
        28: "UT_MOD_SR8",
        30: "UT_MOD_AK103",
        31: "UT_MOD_SPLODED",
        32: "UT_MOD_SLAPPED",
        33: "UT_MOD_SMITED",
        34: "UT_MOD_BOMBED",
        35: "UT_MOD_NUKED",
        36: "UT_MOD_NEGEV",
        37: "UT_MOD_HK69_HIT",
        38: "UT_MOD_M4",
        39: "UT_MOD_GLOCK",
        40: "UT_MOD_COLT1911",
        41: "UT_MOD_MAC11",
        42: "UT_MOD_FLAG",
        43: "UT_MOD_GOOMBA"}

WEAPON_CODES = {
        "ber": "F",
        "de": "G",
        "spas": "H",
        "mp5": "I",
        "ump": "J",
        "hk": "K",
        "lr300": "L",
        "g36": "M",
        "psg": "N",
        "sr8": "Z",
        "ak": "a",
        "negev": "c",
        "m4": "e",
        "glock": "f",
        "colt": "g",
        "mac": "h",
        "he": "O",
        "smoke": "Q",
        "vest": "R",
        "helmet": "W",
        "silencer": "U",
        "laser": "V",
        "med": "T",
        "tacs": "S",
        "ammo": "X",
}

PISTOL_GEAR = ["ber", "de", "glock", "colt", "silencer", "laser", "he", "smoke"]
GRENADE_GEAR = ["he", "smoke", "hk", "ammo"]

